"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { findTeacherStudent, teacherStudents } from "@/lib/teacher-seed";

const gradeLabels = { green: "Passed", yellow: "Needs review", red: "Repeat" };
const sections = ["sabaq", "sabqi", "manzil"];

function Logo() {
  return <Link href="/" className="t-logo"><span>ق</span><strong>Quran<span>Minds</span></strong></Link>;
}

function Icon({ name }) {
  const paths = {
    users: "M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2m7-10a4 4 0 1 0 0-8 4 4 0 0 0 0 8m13 10v-2a4 4 0 0 0-3-3.87m-2-11a4 4 0 0 1 0 7.75",
    calendar: "M3 9h18M7 3v4m10-4v4M5 5h14a2 2 0 0 1 2 2v13H3V7a2 2 0 0 1 2-2",
    chart: "M4 19V10m6 9V5m6 14v-7m5 7H2",
    check: "m5 12 4 4L19 6",
    edit: "M12 20h9M16.5 3.5a2.1 2.1 0 0 1 3 3L7 19l-4 1 1-4z",
    book: "M4 5a3 3 0 0 1 3-3h5v18H7a3 3 0 0 0-3 3zm16 0a3 3 0 0 0-3-3h-5v18h5a3 3 0 0 1 3 3z",
    arrow: "m9 18 6-6-6-6",
    close: "M18 6 6 18M6 6l12 12",
  };
  return <svg aria-hidden="true" width="19" height="19" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d={paths[name]} /></svg>;
}

function RoleEntry() {
  return <main className="role-entry"><div className="role-brand"><Logo /><span className="role-tag">Quran progress, clearly understood.</span></div><section className="role-card"><p className="t-eyebrow">Welcome to Quran Minds</p><h1>How will you use Quran Minds?</h1><p>Choose your view. You can switch roles later from your account.</p><div className="role-grid"><Link href="/teacher" className="role-option featured"><span className="role-icon"><Icon name="users" /></span><div><strong>I am a Teacher</strong><small>Manage classes, daily records, grades, and memorization velocity.</small></div><b>Continue →</b></Link><button className="role-option" disabled><span className="role-icon"><Icon name="users" /></span><div><strong>I am a Parent</strong><small>Follow your child’s progress and attendance.</small></div><b>Coming next</b></button><button className="role-option" disabled><span className="role-icon"><Icon name="book" /></span><div><strong>I am a Student</strong><small>Review assignments and strengthen memorization.</small></div><b>Coming next</b></button></div></section><footer>Verified Quran text · Purpose-built for hifdh programs</footer></main>;
}

function TeacherShell({ active = "class", children }) {
  return <div className="t-app"><aside className="t-sidebar"><Logo /><nav><Link href="/teacher" className={active === "class" ? "active" : ""}><Icon name="users" />My class</Link><span><Icon name="calendar" />Schedule</span><span><Icon name="chart" />Reports</span></nav><div className="t-teacher"><span>UH</span><div><strong>Ustadha Hafsa</strong><small>Al-Noor Academy</small></div></div></aside><div className="t-main"><header className="t-topbar"><div><strong>Hifdh Class A</strong><small>Summer term · 2 active students</small></div><div className="t-top-actions"><span className="source-pill">✓ Verified Quran source</span><Link href="/">Switch role</Link></div></header><main className="t-workspace">{children}</main></div></div>;
}

function GradeDot({ grade, label = true }) {
  return <span className={`t-grade ${grade}`}>{label && gradeLabels[grade]}</span>;
}

function GradeModal({ student, section, onClose, onSave }) {
  const current = student.latest[section].grade;
  const [grade, setGrade] = useState(current);
  return <div className="t-modal-backdrop" role="presentation"><section className="t-modal" role="dialog" aria-modal="true" aria-labelledby="grade-title"><button className="t-modal-close" onClick={onClose} aria-label="Close grade editor"><Icon name="close" /></button><p className="t-eyebrow">Quick grade update</p><h2 id="grade-title">{student.name} · <span className="capitalize">{section}</span></h2><p>Update today’s grade. The full record remains available in the student’s progress screen.</p><div className="modal-grades">{["green", "yellow", "red"].map((value) => <button key={value} className={`${value} ${grade === value ? "selected" : ""}`} onClick={() => setGrade(value)}><i /> <strong>{gradeLabels[value]}</strong><small>{value === "green" ? "Move forward" : value === "yellow" ? "Needs focused review" : "Repeat before new Sabaq"}</small></button>)}</div><div className="modal-actions"><button onClick={onClose}>Cancel</button><button className="t-primary" onClick={() => onSave(grade)}>Save grade</button></div></section></div>;
}

function ClassView() {
  const [students, setStudents] = useState(teacherStudents);
  const [editing, setEditing] = useState(null);
  const saveGrade = (grade) => { setStudents((all) => all.map((student) => student.id === editing.student.id ? { ...student, latest: { ...student.latest, [editing.section]: { ...student.latest[editing.section], grade } } } : student)); setEditing(null); };
  return <TeacherShell><div className="t-heading"><div><p className="t-eyebrow">Sunday, July 12</p><h1>My class</h1><p>Review today’s readiness, attendance, and recent memorization grades.</p></div><button className="t-primary">+ Add student</button></div><section className="t-summary"><div><span><Icon name="users" /></span><strong>2</strong><small>Active students</small></div><div><span><Icon name="check" /></span><strong>94%</strong><small>Average attendance</small></div><div><span><Icon name="book" /></span><strong>20</strong><small>Juz memorized</small></div><div><span><Icon name="chart" /></span><strong>0.78</strong><small>Pages/day average</small></div></section><section className="t-panel class-panel"><div className="class-toolbar"><div><h2>Student overview</h2><p>Click Sabaq, Sabqi, or Manzil to update today’s grade.</p></div><label><span>Search</span><input placeholder="Search students…" /></label></div><div className="class-table"><div className="class-table-head"><span>Student</span><span>Attendance</span><span>Sabaq</span><span>Sabqi</span><span>Manzil</span><span>Level</span><span /></div>{students.map((student) => <div className="class-row" key={student.id}><Link href={`/teacher/students/${student.id}`} className="student-cell"><span className="t-avatar">{student.initials}</span><div><strong>{student.name}</strong><small>{student.current} · {student.totalJuz} Juz complete</small><em>{student.note}</em></div></Link><div className="attendance-cell"><strong>{student.attendance}%</strong><div><i style={{ width: `${student.attendance}%` }} /></div><small>{student.latest.attendance}</small></div>{sections.map((section) => <button key={section} className="grade-button" onClick={() => setEditing({ student, section })}><GradeDot grade={student.latest[section].grade} /><small>Edit</small></button>)}<span className={`level-badge level-${student.level.toLowerCase()}`}>{student.level}</span><Link className="details-link" href={`/teacher/students/${student.id}`}>View/edit details <Icon name="arrow" /></Link></div>)}</div></section>{editing && <GradeModal {...editing} onClose={() => setEditing(null)} onSave={saveGrade} />}</TeacherShell>;
}

function formatDate(date) { return new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric", year: "numeric", timeZone: "UTC" }).format(new Date(`${date}T12:00:00Z`)); }
function rangeText(range) { return `${range.fromSurah} ${range.fromAyah}–${range.toSurah === range.fromSurah ? "" : `${range.toSurah} `}${range.toAyah}`; }

function ProgressTable({ records, onSelect }) {
  return <div className="progress-table"><div className="progress-head"><span>Date</span><span>Attendance</span><span>Sabaq</span><span>Sabqi</span><span>Manzil</span><span>Mistakes</span><span /></div>{records.slice(-18).reverse().map((record) => <button className="progress-row" key={record.id} onClick={() => onSelect(record)}><span><strong>{formatDate(record.date)}</strong><small>{new Intl.DateTimeFormat("en-US", { weekday: "long", timeZone: "UTC" }).format(new Date(`${record.date}T12:00:00Z`))}</small></span><span className={`attendance ${record.attendance.toLowerCase()}`}>{record.attendance}</span>{sections.map((section) => <span key={section}><GradeDot grade={record[section].grade} /><small>{rangeText(record[section].ranges[0])}</small></span>)}<span><strong>{record.mistakes.length}</strong><small>marked words</small></span><span className="row-arrow">›</span></button>)}</div>;
}

function CalendarView({ records, onSelect }) {
  const days = Array.from({ length: 35 }, (_, index) => { const date = new Date(Date.UTC(2026, 5, 28 + index)); const iso = date.toISOString().slice(0, 10); return { date, iso, record: records.find((r) => r.date === iso) }; });
  return <div className="calendar-card"><div className="calendar-title"><button>‹</button><h2>July 2026</h2><button>›</button></div><div className="calendar-weekdays">{["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"].map((day) => <span key={day}>{day}</span>)}</div><div className="calendar-grid">{days.map(({ date, iso, record }) => <button key={iso} className={`${date.getUTCMonth() !== 6 ? "muted" : ""} ${record ? "has-record" : ""}`} disabled={!record} onClick={() => record && onSelect(record)}><strong>{date.getUTCDate()}</strong>{record ? <><div className="calendar-grades">{sections.map((s) => <i key={s} className={record[s].grade} />)}</div><small>{record.dailyPages ? `${record.dailyPages} pg` : "No Sabaq"}</small></> : null}</button>)}</div></div>;
}

function RangeEditor({ label, value, onChange, juzBounds }) {
  const [mode, setMode] = useState(value.preset || "range");
  const updateRange = (index, key, next) => onChange({ ...value, ranges: value.ranges.map((range, i) => i === index ? { ...range, [key]: next } : range) });
  const applyJuz = (juz) => { const bound = juzBounds.find((item) => item.juz === Number(juz)); if (!bound) return; onChange({ ...value, juz: Number(juz), ranges: [{ fromSurah: bound.from.surahName, fromAyah: bound.from.ayah, toSurah: bound.to.surahName, toAyah: bound.to.ayah }] }); };
  return <section className="daily-section"><div className="daily-section-head"><div><h3>{label}</h3><GradeDot grade={value.grade} /></div>{label === "Manzil" && <div className="preset-tabs">{["range", "1/2 juz", "1 juz"].map((item) => <button key={item} className={mode === item ? "active" : ""} onClick={() => { setMode(item); onChange({ ...value, preset: item }); }}>{item}</button>)}</div>}</div>{label === "Manzil" && mode !== "range" && <label className="juz-select">Select Juz<select value={value.juz || 26} onChange={(event) => applyJuz(event.target.value)}>{juzBounds.map((bound) => <option key={bound.juz} value={bound.juz}>Juz {bound.juz} · {bound.from.surahName} {bound.from.ayah} to {bound.to.surahName} {bound.to.ayah}</option>)}</select></label>}<div className="ranges">{value.ranges.map((range, index) => <div className="range-row" key={index}><span>{index + 1}</span><label>From surah<input value={range.fromSurah} onChange={(e) => updateRange(index, "fromSurah", e.target.value)} /></label><label>Ayah<input type="number" value={range.fromAyah} onChange={(e) => updateRange(index, "fromAyah", Number(e.target.value))} /></label><b>→</b><label>To surah<input value={range.toSurah} onChange={(e) => updateRange(index, "toSurah", e.target.value)} /></label><label>Ayah<input type="number" value={range.toAyah} onChange={(e) => updateRange(index, "toAyah", Number(e.target.value))} /></label>{value.ranges.length > 1 && <button aria-label={`Remove ${label} range ${index + 1}`} onClick={() => onChange({ ...value, ranges: value.ranges.filter((_, i) => i !== index) })}>×</button>}</div>)}<button className="add-range" onClick={() => onChange({ ...value, ranges: [...value.ranges, { fromSurah: "", fromAyah: 1, toSurah: "", toAyah: 1 }] })}>+ Add another range</button></div></section>;
}

function DayDetail({ initial, onBack, juzBounds }) {
  const [record, setRecord] = useState(initial); const [editing, setEditing] = useState(false); const [saved, setSaved] = useState(false);
  return <div><button className="back-link" onClick={onBack}>← Back to progress</button><div className="day-heading"><div><p className="t-eyebrow">Daily record</p><h2>{formatDate(record.date)}</h2><p>{record.attendance} · {record.dailyPages} pages memorized · {record.mistakes.length} marked mistakes</p></div><button className={editing ? "t-primary" : "t-secondary"} onClick={() => { if (editing) setSaved(true); setEditing(!editing); }}>{editing ? "Save daily record" : <><Icon name="edit" /> Edit record</>}</button></div>{saved && !editing && <div className="saved-banner">✓ Daily record saved for {formatDate(record.date)}</div>}<div className={`daily-record ${editing ? "editing" : ""}`}>{editing ? sections.map((section) => <RangeEditor key={section} label={section[0].toUpperCase() + section.slice(1)} value={record[section]} juzBounds={juzBounds} onChange={(next) => setRecord({ ...record, [section]: next })} />) : sections.map((section) => <section className="daily-section" key={section}><div className="daily-section-head"><div><h3 className="capitalize">{section}</h3><GradeDot grade={record[section].grade} /></div>{record[section].preset && <span className="preset-label">{record[section].preset} · Juz {record[section].juz}</span>}</div>{record[section].ranges.map((range, i) => <div className="readonly-range" key={i}><span>{i + 1}</span><strong>{rangeText(range)}</strong></div>)}</section>)}<section className="daily-section mistakes-section"><div className="daily-section-head"><div><h3>Marked mistakes</h3><span>{record.mistakes.length} words</span></div></div>{record.mistakes.length ? record.mistakes.map((mistake, index) => <div className="mistake-row" key={index}><span>{index + 1}</span><strong>{mistake.type}</strong><small>Word position {mistake.wordIndex}</small></div>) : <p>No mistakes recorded for this day.</p>}</section></div></div>;
}

function VelocityChart({ student, projected }) {
  const history = student.history.filter((_, index) => index % 9 === 0).slice(-18);
  const values = history.map((record) => record.pagesMemorized);
  const min = Math.min(...values); const max = Math.max(...values); const points = values.map((value, i) => `${30 + i * 34},${180 - ((value - min) / Math.max(1, max - min)) * 125}`).join(" ");
  const lastX = 30 + (values.length - 1) * 34; const lastY = 55; const future = Array.from({ length: 7 }, (_, i) => `${lastX + i * 34},${lastY - i * 5}`).join(" ");
  return <section className="velocity-panel"><div className="velocity-head"><div><h2>{projected ? "All-inclusive projection" : "Historical Sabaq velocity"}</h2><p>{projected ? "Actual memorization plus a forward estimate at the current weighted average." : "Cumulative pages memorized across recorded class days."}</p></div><span className={`trend ${student.id === "layina" ? "up" : "flat"}`}>{student.id === "layina" ? "↗ Increasing" : "→ Mostly flat"}</span></div><svg viewBox="0 0 850 230" role="img" aria-label={`${student.name} memorization velocity`}><line x1="30" y1="180" x2="820" y2="180" stroke="#dfe8e3"/><line x1="30" y1="120" x2="820" y2="120" stroke="#edf2ef"/><line x1="30" y1="60" x2="820" y2="60" stroke="#edf2ef"/><polyline points={points} fill="none" stroke="#176a46" strokeWidth="4" strokeLinejoin="round" strokeLinecap="round"/>{projected && <polyline points={`${lastX},${lastY} ${future}`} fill="none" stroke="#176a46" strokeWidth="3" strokeDasharray="8 8" strokeLinecap="round"/>}<circle cx={lastX} cy={lastY} r="6" fill="#176a46"/></svg><div className="velocity-legend"><span><i className="solid" />Recorded progress</span>{projected && <span><i className="dotted" />Projected at {student.id === "layina" ? "1.0" : "0.55"} pages/day</span>}<strong>{student.totalJuz} Juz memorized</strong></div></section>;
}

function StudentView({ studentId, juzBounds }) {
  const student = findTeacherStudent(studentId); const [tab, setTab] = useState("records"); const [layout, setLayout] = useState("list"); const [selected, setSelected] = useState(null); const [projection, setProjection] = useState(true);
  const stats = useMemo(() => { const recent = student.history.slice(-25); return { avg: (recent.reduce((sum, item) => sum + item.dailyPages, 0) / recent.filter((r) => r.attendance !== "Absent").length).toFixed(2), mistakes: recent.reduce((sum, item) => sum + item.mistakes.length, 0) }; }, [student]);
  return <TeacherShell active="student"><div className="student-header"><Link href="/teacher">← My class</Link><div className="student-title"><span className="t-avatar large">{student.initials}</span><div><p className="t-eyebrow">Student progress</p><h1>{student.name}</h1><p>{student.totalJuz} Juz memorized · Juz {student.memorizedJuz} · Level {student.level}</p></div></div><button className="t-secondary"><Icon name="edit" /> Edit student</button></div><section className="student-stats"><div><small>Current Sabaq</small><strong>{student.current}</strong><GradeDot grade={student.latest.sabaq.grade} /></div><div><small>30-day velocity</small><strong>{stats.avg} pages/day</strong><span className="positive">↗ Building steadily</span></div><div><small>Attendance</small><strong>{student.attendance}%</strong><span>Current term</span></div><div><small>Recent mistakes</small><strong>{stats.mistakes}</strong><span>Last 25 records</span></div></section><div className="student-tabs"><button className={tab === "records" ? "active" : ""} onClick={() => { setTab("records"); setSelected(null); }}>Daily progress</button><button className={tab === "velocity" ? "active" : ""} onClick={() => setTab("velocity")}>Sabaq velocity</button></div>{tab === "records" ? selected ? <DayDetail initial={selected} onBack={() => setSelected(null)} juzBounds={juzBounds} /> : <section className="t-panel records-panel"><div className="records-toolbar"><div><h2>Progress history</h2><p>Select a day to view or edit Sabaq, Sabqi, Manzil, and mistakes.</p></div><div className="view-toggle"><button className={layout === "list" ? "active" : ""} onClick={() => setLayout("list")}>☷ List</button><button className={layout === "calendar" ? "active" : ""} onClick={() => setLayout("calendar")}><Icon name="calendar" /> Calendar</button></div></div>{layout === "list" ? <ProgressTable records={student.history} onSelect={setSelected} /> : <CalendarView records={student.history} onSelect={setSelected} />}</section> : <div><div className="projection-toggle"><button className={!projection ? "active" : ""} onClick={() => setProjection(false)}>Historical</button><button className={projection ? "active" : ""} onClick={() => setProjection(true)}>All-inclusive + forecast</button></div><VelocityChart student={student} projected={projection} /><section className="forecast-cards"><div><small>Current pace</small><strong>{student.id === "layina" ? "1.0" : "0.55"} pages/day</strong><p>Weighted from present attendance and recent Sabaq.</p></div><div><small>Trend</small><strong>{student.id === "layina" ? "Increasing" : "Mostly flat"}</strong><p>Compared with the previous 60 class days.</p></div><div><small>Estimated completion</small><strong>{student.id === "layina" ? "Feb 2028" : "Oct 2030"}</strong><p>Projection updates as new daily records are saved.</p></div></section></div>}</TeacherShell>;
}

export default function TeacherProgressApp({ view, studentId, juzBounds = [] }) {
  if (view === "roles") return <RoleEntry />;
  if (view === "student") return <StudentView studentId={studentId} juzBounds={juzBounds} />;
  return <ClassView />;
}
